import { RouteInfo } from './sidebar.metadata';
export const ROUTES: RouteInfo[] = [
  {
    path: 'home',
    title: 'Inicio',
    moduleName: 'pacient',
    iconType: 'material-icons-two-tone',
    icon: 'home',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
  },
  {
    path: 'appointment',
    title: 'Agendar Cita',
    moduleName: 'pacient',
    iconType: 'material-icons-two-tone',
    icon: 'event',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
  },
  {
    path: 'laboratory',
    title: 'Laboratorio',
    moduleName: 'pacient',
    iconType: 'material-icons-two-tone',
    icon: 'biotech',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
  },
  {
    path: 'diary',
    title: 'Agenda Virtual',
    moduleName: 'pacient',
    iconType: 'material-icons-two-tone',
    icon: 'book',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
  },
  {
    path: 'pharmacy',
    title: 'Farmacia',
    moduleName: 'pacient',
    iconType: 'material-icons-two-tone',
    icon: 'vaccines',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
  },
  {
    path: 'prescription',
    title: 'Recetas',
    moduleName: 'pacient',
    iconType: 'material-icons-two-tone',
    icon: 'assignment',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
  }
];
