import { RouteInfo } from './sidebar.metadata';
export const ROUTES: RouteInfo[] = [
  {
    path: 'home',
    title: 'Inicio',
    moduleName: 'admin',
    iconType: 'material-icons-two-tone',
    icon: 'home',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
  },
  {
    path: 'patients',
    title: 'Pacientes',
    moduleName: 'admin',
    iconType: 'material-icons-two-tone',
    icon: 'person',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
  },
  {
    path: 'doctor',
    title: 'Doctores',
    moduleName: 'admin',
    iconType: 'material-icons-two-tone',
    icon: 'masks',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
  },
  {
    path: 'typeLaboratory',
    title: 'Tipo de Laboratorios',
    moduleName: 'admin',
    iconType: 'material-icons-two-tone',
    icon: 'science',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
  },
  {
    path: 'medicament',
    title: 'Medicamentos',
    moduleName: 'admin',
    iconType: 'material-icons-two-tone',
    icon: 'medication',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
  },
  {
    path: 'typeMedicament',
    title: 'Tipo de Medicamentos',
    moduleName: 'admin',
    iconType: 'material-icons-two-tone',
    icon: 'medication_liquid',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
  },
  {
    path: 'speciality',
    title: 'Especialidades',
    moduleName: 'admin',
    iconType: 'material-icons-two-tone',
    icon: 'local_pharmacy',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
  },
  {
    path: 'appointment',
    title: 'Citas',
    moduleName: 'admin',
    iconType: 'material-icons-two-tone',
    icon: 'today',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
  },
  {
    path: 'laboratory',
    title: 'Laboratorios',
    moduleName: 'admin',
    iconType: 'material-icons-two-tone',
    icon: 'biotech',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
  },
];
